# Generated by Django 5.0.7 on 2024-07-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_payment_session_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
    ]
