# Generated by Django 5.0.7 on 2024-07-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_remove_payment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="type",
            new_name="pay_type",
        ),
    ]
