# Generated by Django 5.0.7 on 2024-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("PAID", "PAID"),
                    ("EXPIRED", "EXPIRED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
